### PR TITLE
Resrickli gigmap

### PR DESCRIPTION
**Pull request by resrickli**
New features for gigpress:
- Overview map
- Vicinity search
- Possibility to display Radio/TV Shows separately from live shows
- ...
See readme.txt

### CODE REVIEW

**Comment by zbtirrell** [comment]
Note for code reviewers: this is more easily reviewed with ?w=1 as there are numerous whitespace changes here.

**Comment by barryhughes** [comment]
Hey @resrickli,

Thanks for submitting this! It packs in a lot of changes 😄 

I wonder though if you might be able to break this apart and submit smaller PRs, each covering a single feature? This would make it much easier and faster for us to review. I do also have a couple of other notes:

1) We greatly prefer flat structures over nested structures. Examples:

```php
// Nested style
function take_action() {
    if ( $something ) {
        if ( $other ) {
            do_something();
        }
    }
}

// Flattened style (preferred)
function take_action() {
    if ( ! $something || ! $other ) {
        return;
    }

    do_something();
}
```

2) Where it makes sense we'd rather see WordPress's API being used in preference to directly using functions that might not be available on all installations. An example could be using the cURL extension (in which case we'd rather see the `wp_remote_*()` family of functions being used).

3) Last but by no means least, though I fully realize existing code within this project may follow different conventions, for any new code that we add it would be great to follow the coding standards [outlined here.](http://moderntribe.github.io/products-engineering/php/)

Thanks again!

**Comment by resrickli** [comment]
Barry, you are asking a lot!
I am afraid I will mot meet your expectations - honestly, I wonder, where from I should get the motivation to do so:

It is difficult to break the pack apart into smaller PRs. The only thing I can offer is the version I sent to Derek Hogue in February 2015. It contains all the changes for the map display, based on version 2.3.7 of gigpress (now, we are at 2.3.17). At the time Derek already had no time left to maintain gigpress.

1) In contrast to you I greatly prefer nested structure over flat ones. In my opinion nested structures are easier to check for completeness (are all cases covered?), to test and to debug. I do not intend to change this.

2) Thank you for the comment on using WordPress's API functions. This is the only point where I might change the code.

3) Coding standards make a lot of sense for the employees of an organisation. However, I made the extensions to gigpress as much as possible in the same coding style as Derek Hogue did. If we wanted to make it compatible to modern tribes' coding standards, we would have to change the entire code of gigpress. A lot of effort just for the beauty of it!

**Comment by barryhughes** [comment]
I appreciate your perspective on this and the time you have already invested but, without further changes, it is unlikely we can merge this in.

Setting aside any other points, breaking this up into smaller PRs - each targeting a single feature - would make it far easier for us to review and provide you with more specific feedback. I do understand that means more work for you, but it looks like quite a few changes would be required before we could accept this and from our perspective a set of smaller and more focused PRs would be the most time efficient way to do things.

**Comment by resrickli** [comment]
I understand your point of view. However, if I invest more work into this project,  then I will do it to bring it forward, to add new features or to maintain its compatibility.  Let's forget it.

**Pull request closed without merging**
